# Jekyll configuration

name: 大美•海洋
description: Software Developer

# Url is currently only used only for the RSS feed in feed.xml
url: http://chencxiocas.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
#baseurl: '/jekyll-clean-dark'
baseurl:

social:
  github: chencxiocas
  stackoverflow: ''
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest:
  email: true

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: chencxiocas
comments: true

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
gems: [jekyll-paginate]
paginate: 10

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
